### ISSUE TITLE
Sharing this codebase with Julia community

### ISSUE THREAD

**Issue by zlatanvasovic** [zyth0s/SciAlgs.jl#1]
It seems this repository is obscure. I found it by chance, by searching "julia chemistry" on GitHub. Sharing the repository with the Julia community would be beneficial for both you as the author and for the methods presented in the repository. The best places for that are [Julia Discourse](https://discourse.julialang.org/) and [juliabloggers](https://www.juliabloggers.com/).

By the way, did you write all Julia implementations yourself, or you copied some from somewhere else?

I had to contact you this way since I couldn't find any other method (email, website) on your profile.

**Comment by zyth0s** [comment]
Hello Zlatan,

Thank you for the interest in the repository. I must say that it is under development, far from being a standalone package. My experience with Julia is relatively short, so I do not know how to properly develop packages. In particular, I am not sure now if I want it to be a package. It is becoming more like a collection of diverse scripts. Some were written by me before in another language and now translated. Others are inspired by implementations in other languages. I am also writing new ones.

Whenever I found inspiration in other codes or I just compiled code from elsewhere, I try to state the reference with links and/or citations, inside the file or with a link in the README.md. For example, Algorithms from THE BOOK, and Computational Fluid Dynamics Course were not written by me, but I thought that it would be beneficial to pack them together. The first is not in this site, so I have put it in a folder. The second has a repository, so I simply put the link. In both cases the README.md shows a link to the authors sites. The rest were mostly written by me with some exceptions. However, judging by your comment my efforts were not enough.

I am aware of Julia Slack, Discourse and juliabloggers. It is simply that I didn't take it seriously enough to pursue the development of a package. The original idea I had in mind has changed. At the beginning I had the intention of just
collecting my scripts but later I decided to make a collection of programs with an educative purpose, for me and the rest,
whether they were written by me or not. For instance, I would be interested in sharing it and learning from other's opinions about how to manage the repository, be honest with the original sources of those programs that are not mine, ...

You can contact me through e-mail: danielmail7@gmail.com.

**Comment by zlatanvasovic** [comment]
Alright, thanks. I'll move this to email.
